# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
pod 'Firebase/Core'

target 'Critchlore' do
end

target 'CritchloreTests' do
end

target 'CritchloreUITests' do
end

